### PR TITLE
load data into the grid from URL params

### PR DESCRIPTION
**Pull request by dr-pickles**
- added an example program that converts Fahrenheit to Celsius
- click 'Example' link on the index page to open it
- the cell data is stored in the href attribute of the 'Example' link
- function ip_LoadDataFromQueryString extracts the query string from the URL and populates the grid cells with the relevant data

### CODE REVIEW

**Review by DrChrisHarte — APPROVED** [review]
Awesome! you're on fire right now!

**Comment by dr-pickles** [comment]
- click 'copy contents' button to generate a query string
- the encoded query string is copied into clipboard
- paste it in the URL after ? to load the program

**Comment by DrChrisHarte** [comment]
This is really cool! well done :)

I think we can make a very slight change to make the UX make more sense.  If you change example.html to be called sheet.html then that can become the main "spreadsheet" page that people interact with.  Now, when you click the "copy to clipboard" button, it wants to have the full URL rather than just the params e.g. "lattice-lang.github.io/sheet.html?<params>" so that if someone clicks that button, they instantly have a shareable link that they can use to get back to their own work or give to others to see what they've done.  It makes creating examples for lattice really easy because you can create them on the sheet and tweak as required then just get the link to add to the index.html.   I think index.html wants to be a landing page that maybe wants a picture of the spreadsheet in use and some other blurb but not the executable sheet itself - may as well just keep that on sheet.html for simplicity.   Hope that all makes sense. 

Hmm , I note that there's a bit of explanation on the example.html page - maybe we allow people to put a title and description on their sheet and save as part of the URL params as well, or should we just put that description on the sheet itself as comments maybe?

**Comment by DrChrisHarte** [comment]
I've also just noticed that column widths are not recorded in the URL params so loading a sheet where the user had edited them doesn't bring back exactly the same thing... row height will be similar.   That can be a separate PR though :)

**Pull request merged**
